/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountManager: typeof import('./src/components/AccountManager.vue')['default']
    AddBillPopup: typeof import('./src/components/AddBillPopup.vue')['default']
    BillItem: typeof import('./src/components/BillItem.vue')['default']
    BudgetProgress: typeof import('./src/components/BudgetProgress.vue')['default']
    CategoryManager: typeof import('./src/components/CategoryManager.vue')['default']
    CategoryPicker: typeof import('./src/components/CategoryPicker.vue')['default']
    ChatBubble: typeof import('./src/components/ChatBubble.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    MonthPicker: typeof import('./src/components/MonthPicker.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanPopup: typeof import('vant/es')['Popup']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
